services:
  - type: web
    name: quantum-simulator
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build
    startCommand: gunicorn app:app
    workingDir: backend 
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildFilter:
      paths:
        - frontend/**
        - backend/**
        - requirements.txt
    plan: free